// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VictoryRestaurant.Foods.Infrastructure.Context;

#nullable disable

namespace VictoryRestaurant.Foods.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VictoryRestaurant.Foods.Domain.Entities.FoodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("Cost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal")
                        .HasDefaultValue(0m)
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("FoodTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("food_type_id");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("FoodTypeId");

                    b.ToTable("foods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfef12be-cb69-4bde-afb1-0be5138d2d56"),
                            Cost = 5m,
                            CreatedDate = new DateTime(2023, 2, 10, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3028),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("07b99162-3f42-4ba3-a3a5-f371c2439f3e"),
                            ImagePath = "",
                            Name = "Omelet"
                        },
                        new
                        {
                            Id = new Guid("bcd425c5-b34d-4e81-a3f7-43d2a2bcfe39"),
                            Cost = 2.5m,
                            CreatedDate = new DateTime(2023, 2, 9, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3054),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("07b99162-3f42-4ba3-a3a5-f371c2439f3e"),
                            ImagePath = "",
                            Name = "Yogurt"
                        },
                        new
                        {
                            Id = new Guid("c393991e-ec78-4820-a1bb-22d965955d87"),
                            Cost = 3m,
                            CreatedDate = new DateTime(2023, 2, 8, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3058),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("07b99162-3f42-4ba3-a3a5-f371c2439f3e"),
                            ImagePath = "",
                            Name = "Porridge"
                        },
                        new
                        {
                            Id = new Guid("2d8ae5bc-91d6-4fbf-a26e-f47bfd66878d"),
                            Cost = 5m,
                            CreatedDate = new DateTime(2023, 2, 7, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3060),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("07b99162-3f42-4ba3-a3a5-f371c2439f3e"),
                            ImagePath = "",
                            Name = "Cornflakes"
                        },
                        new
                        {
                            Id = new Guid("0af0ca02-3490-4d94-8f4b-3166fc776fad"),
                            Cost = 7m,
                            CreatedDate = new DateTime(2023, 2, 6, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3063),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("bec4597e-cf4d-4ee8-b25c-938a7b008843"),
                            ImagePath = "",
                            Name = "Soup"
                        },
                        new
                        {
                            Id = new Guid("74e9d378-61cd-4fa2-9845-60585e68d4de"),
                            Cost = 15m,
                            CreatedDate = new DateTime(2023, 2, 5, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3065),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("bec4597e-cf4d-4ee8-b25c-938a7b008843"),
                            ImagePath = "",
                            Name = "Beef steak"
                        },
                        new
                        {
                            Id = new Guid("077d0979-0509-4f7d-9177-2e4265ac9455"),
                            Cost = 10m,
                            CreatedDate = new DateTime(2023, 2, 4, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3067),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("bec4597e-cf4d-4ee8-b25c-938a7b008843"),
                            ImagePath = "",
                            Name = "Pilaf"
                        },
                        new
                        {
                            Id = new Guid("8ad21ff8-43c4-45b6-b2fa-6a2e4c8e31a6"),
                            Cost = 10m,
                            CreatedDate = new DateTime(2023, 2, 3, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3070),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("bec4597e-cf4d-4ee8-b25c-938a7b008843"),
                            ImagePath = "",
                            Name = "Fried potatoes"
                        },
                        new
                        {
                            Id = new Guid("9fb0dd01-f428-401c-8ef5-487c1e696148"),
                            Cost = 100m,
                            CreatedDate = new DateTime(2023, 2, 2, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3072),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("c96a0d80-70cd-4cae-b30d-e4258d500660"),
                            ImagePath = "",
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = new Guid("776509a9-a398-4e6e-98e9-84f7d3d9ca73"),
                            Cost = 30m,
                            CreatedDate = new DateTime(2023, 2, 1, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3074),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("c96a0d80-70cd-4cae-b30d-e4258d500660"),
                            ImagePath = "",
                            Name = "Kutab"
                        },
                        new
                        {
                            Id = new Guid("ea04611a-8bdf-4971-a64f-fc2c937e2bb6"),
                            Cost = 15m,
                            CreatedDate = new DateTime(2023, 1, 30, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3077),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("c96a0d80-70cd-4cae-b30d-e4258d500660"),
                            ImagePath = "",
                            Name = "Tar-tar"
                        },
                        new
                        {
                            Id = new Guid("a49e8820-e12c-4143-a3bb-f34438cb16fc"),
                            Cost = 15m,
                            CreatedDate = new DateTime(2023, 1, 29, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3079),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("c96a0d80-70cd-4cae-b30d-e4258d500660"),
                            ImagePath = "",
                            Name = "Bruschetta"
                        },
                        new
                        {
                            Id = new Guid("b4cb3838-eef3-4055-9bd0-a1cb6c44359a"),
                            Cost = 5m,
                            CreatedDate = new DateTime(2023, 1, 28, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3082),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("e8cfab89-854a-4899-8ffd-59b6048de3cf"),
                            ImagePath = "",
                            Name = "Ice cream"
                        },
                        new
                        {
                            Id = new Guid("dff85745-bf12-4aa9-b449-745cea831894"),
                            Cost = 10m,
                            CreatedDate = new DateTime(2023, 1, 27, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3084),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("e8cfab89-854a-4899-8ffd-59b6048de3cf"),
                            ImagePath = "",
                            Name = "Cake"
                        },
                        new
                        {
                            Id = new Guid("4e3bbbf4-e6e1-4914-9125-215237e76404"),
                            Cost = 6m,
                            CreatedDate = new DateTime(2023, 1, 26, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3086),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("e8cfab89-854a-4899-8ffd-59b6048de3cf"),
                            ImagePath = "",
                            Name = "Cheesecake"
                        },
                        new
                        {
                            Id = new Guid("0ba1411c-5ec2-4ed3-9c14-b4509f7a45df"),
                            Cost = 6m,
                            CreatedDate = new DateTime(2023, 1, 25, 16, 0, 48, 846, DateTimeKind.Local).AddTicks(3088),
                            Description = "So tasty!",
                            FoodTypeId = new Guid("e8cfab89-854a-4899-8ffd-59b6048de3cf"),
                            ImagePath = "",
                            Name = "Muesli"
                        });
                });

            modelBuilder.Entity("VictoryRestaurant.Foods.Domain.Entities.FoodTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("food_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("07b99162-3f42-4ba3-a3a5-f371c2439f3e"),
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("bec4597e-cf4d-4ee8-b25c-938a7b008843"),
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = new Guid("c96a0d80-70cd-4cae-b30d-e4258d500660"),
                            Name = "Dinner"
                        },
                        new
                        {
                            Id = new Guid("e8cfab89-854a-4899-8ffd-59b6048de3cf"),
                            Name = "Desert"
                        });
                });

            modelBuilder.Entity("VictoryRestaurant.Foods.Domain.Entities.FoodEntity", b =>
                {
                    b.HasOne("VictoryRestaurant.Foods.Domain.Entities.FoodTypeEntity", "FoodType")
                        .WithMany()
                        .HasForeignKey("FoodTypeId");

                    b.Navigation("FoodType");
                });
#pragma warning restore 612, 618
        }
    }
}
