name: Continious-Integration

on:
  push:
    branches:
  - master


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install .NET
    uses: actions/setup-dotnet@v3
    with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
    run: dotnet restore
    - name: Build
    run: dotnet build --no-restore
    - name: Test
    run: dotnet test --no-build --verbosity normal

  linter:
    runs-on: ubuntu-latest