on:
 workflow_dispatch:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]

jobs:
  manualjob:
    name: manualjob
    runs-on: ubuntu-latest
    steps:
    - name: manualapproove
    run: Manually approved
  test:
    name: test
    needs: manualjob
    if: "!contains(github.event.pull_request.labels.*.name, '0 diff trivial')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: | 
        dotnet restore ./VictoryRestaurant.Foods.sln 
        dotnet build src/VictoryRestaurant.Foods.Presentation/VictoryRestaurant.Foods.Presentation.csproj --configuration Release --no-restore
    - name: Testing
      run: dotnet test ./VictoryRestaurant.Foods.sln --configuration Release --no-restore

  linter:
    name: linter
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Lint
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#name: .NET Core
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#jobs:
#  build_web_app1:
#    name: Build WebApp1
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
      
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 3.1.101
 
#    - name: Install dependencies
#      run: dotnet restore ${{ github.workspace }}/src/WebApp1/WebApp1.csproj
      
#    - name: Build
#      run: dotnet build ${{ github.workspace }}/src/WebApp1/WebApp1.csproj --configuration Release --no-restore
      
#    - name: Test
#      run: dotnet test ${{ github.workspace }}/src/WebApp1/WebApp1.csproj --no-restore --verbosity normal
#    - name: Publish
#      run: dotnet publish ${{ github.workspace }}/src/WebApp1/WebApp1.csproj
    
#    - name: Upload Build Artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: WebApp1
#        path: ${{ github.workspace }}/src/WebApp1/bin/Debug/netcoreapp3.1/publish/
        
#  build_web_app2:
#    name: Build WebApp2
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
      
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 3.1.101
 
#    - name: Install dependencies
#      run: dotnet restore ${{ github.workspace }}/src/WebApp2/WebApp2.csproj
      
#    - name: Build
#      run: dotnet build ${{ github.workspace }}/src/WebApp2/WebApp2.csproj --configuration Release --no-restore
      
#    - name: Test
#      run: dotnet test ${{ github.workspace }}/src/WebApp2/WebApp2.csproj --no-restore --verbosity normal
#    - name: Publish
#      run: dotnet publish ${{ github.workspace }}/src/WebApp2/WebApp2.csproj
       
#    - name: Upload Build Artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: WebApp2
#        path: ${{ github.workspace }}/src/WebApp2/bin/Debug/netcoreapp3.1/publish/